Homework3.Kushnir
ArtemKushnir/spbu_pyhton_sem1 pull request #10
Opened 2023-10-08 22:18 UTC by ArtemKushnir

Я долго думал, но не придумал, как нам обрабатывать случай в curry_explicit, когда арность n, а подают >n аргументов

2023-10-16 19:54 UTC, toadharvard requested changes

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +    def accept_arguments(args):
Странное название, то что аргументы принимает и так понятно

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +            return function()
Вызов вместо возврата

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +            while True:
Тут бред какой-то. Цикл бесполезные абсолютно. Объясни зачем добавил в комментах

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +                f_args += [args]
Есть append. А вот это перестраивает список с нуля

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +                    result = f_args
Какая-то магическая глобальная переменная перепиши без nonlocal

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +            return "arity cannot be negative"
Вызови исключение. Кто вообще от функции каррирования ожидает строку?

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +            return "arity cannot be negative"
raise ValueEror(...)

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +            return "arity cannot be negative"
Опять строка

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +            return "incorrect arity"
Тоже строка

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +        else:
Else не нужен

2023-10-16 19:54 UTC, toadharvard commented on src/Homeworks/Homework3/Curry.py
> +                    return function(i)
Это тупо не работает. Ты запускал хоть на каких-то тестах?

2023-10-17 10:01 UTC, ArtemKushnir commented on src/Homeworks/Homework3/Curry.py
> +            while True:
Я постарался понять, зачем я его добавил, но не понял, переклинило меня что-то

2023-10-17 19:55 UTC, toadharvard approved these changes

2023-10-19 13:23 UTC, SpirinEgor approved these changes

2023-10-19 13:23 UTC, merged