Homework4.Task1.Kushnir
ArtemKushnir/spbu_pyhton_sem1 pull request #12
Opened 2023-10-15 21:46 UTC by ArtemKushnir

2023-10-28 11:22 UTC, toadharvard requested changes

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +        negative_number2 = (
Нормально сбилдь лист, ты тут минимум трижды пересоздаешь лист

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +        sign = [1, 0]
Почему под знак 2 числа в массиве?

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +def transformation_to_additional(number):
Эта функция должна переводить в обратный код и прибавлять 1
Почему тут в else ветке кринж какой-то?
А еще сама ветка else не нужна

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    for i in range(len(number1) - 1, -1, -1):
эти ифы заменяются на % спокойно

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    else:
else не нужен

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    else:
не нужен

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    elif len(number2) > len(number1):
нужен if

2023-10-28 11:22 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +        number1 = [number1[0]] + [0] * (len(number2) - len(number1)) + number1[1:]
вот это все в отдельную функциюю с нормальным названием

2023-11-02 21:54 UTC, toadharvard requested changes

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    for i in range(len(number1) - len(number2)):
Во-первых, цикл не нужен. Ты и так  знаешь разницу.
Во-вторых, Если бы ты хранил числа в обратном порядке, то insert не занимал бы O(n) времени, т.к превратился бы в append.

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +def add_digits_to_second_number(number1, number2, negative_number2):
Сигнатура функции кринж. Откуда там негативное число взялось вообще.
Почему ты возвращаешь такую пару, а не другую, теряя информацию о number1

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +def add_digits_to_first_number(number1, number2):
Чем это отличается по смыслу от  add_digits_to_first_number?
Ничем, только порядком, лол. Что мешает передать аргументы в другом порядке?

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +def add_digits_to_second_number(number1, number2, negative_number2):
По названию аргументов неясно, что туда будет передано совсем не число int, а массив

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +def calculate_final_number(number1, number2):
Ну такое, как будто бы смешал библиотеку для обработки двоичных чисел и конкретное задание по сумме и разнице.

Особенно заметно тут
```python
    if len(direct_code1) > len(direct_code2):
        direct_code2, direct_negative_code2 = add_digits_to_second_number(
            direct_code1, direct_code2, direct_negative_code2
        )
 ```

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +def calculate_final_number(number1, number2):
Выглядит откровенно плохо из-за этого

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    if not first_number.lstrip("-").isdigit():
Лучше бы функцию обработки ввода вынес, чем вывода на экран.

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    if not first_number.lstrip("-").isdigit():
Кроме того, такая проверка на float невалидна для множества кейсов. Используй исключения и float()

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +def output_numbers_and_calculations(
Зачем это выносить пользователю?
Количество аргументов такое большое, так как ты их просто из функции в функцию перекладываешь.

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    for i in range(len(number1) - 1, -1, -1):
А хранил бы в обратном порядке, не имел бы странных for'oв

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +        if adding_digit > 1:
count = adding_digit // 2

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    print(f"{number1} + {number2} = {number1 + number2}")
Нет, это кринж. Ты должен уметь складывать в бинарной форме и переводить из бинарной формы в десятичную.
Нет никакой гарантии, что ответ, который ты в двоичном виде посчитал ДЕЙСТВИТЕЛЬНО такой в десятичном виде

2023-11-02 21:54 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +        number = abs(number)
это тут лишнее, вынеси за условие это присваивание

2023-11-12 13:33 UTC, toadharvard requested changes
Реально странная логика. Добавляешь нолик, убираешь нолик. Потом в add digits  у тебя местами меняются sign и 0. Короче говоря, это плохо.

2023-11-12 13:33 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +        for i in range(len(number_array)):
Второй раз этот цикл используешь, можно было вынести в отдельную функцию reverse_binary

2023-11-12 13:33 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    bit.append(0)
Зачем?

2023-11-12 13:33 UTC, toadharvard commented on src/Homeworks/Homework4/Binary_calculator.py
> +    sign = number_array[-1]
Надо строчки местами поменять, а то это так-то не sign нифига получается, ты ведь берешь последний элемент от списка, у которого строчкой выше убрал последний элемент🗿

2023-11-27 18:41 UTC, SpirinEgor commented
3 ревью позади, а комментарии остались 🫠
Правила есть правила 🤷‍♂️

2023-11-27 18:41 UTC, closed without merging