Homework4.task2
ArtemKushnir/spbu_pyhton_sem1 pull request #14
Opened 2023-10-25 00:27 UTC by ArtemKushnir

2023-11-14 22:35 UTC, Arsene-Baitenov requested changes
🤮🤮🤮

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +        form = int(input("select the output format: "))
![image](https://github.com/ArtemKushnir/spbu_pyhton_sem1/assets/91395485/aff8b7f3-fc49-439a-b787-9e8ec1a56dee)

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +        real_number = float(input())
Ввод _inf_ в качестве числа обваливает программу

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +        print("not a number")
Ошибка выпадет и в случае ввода белиберды в качестве формата. Нужно выводить разные сообщения для разных ошибок

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +def main_func(number, format_number):
если функция выдаёт то что надо выводить, почему она названа `main_func`?

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +    whole_part, fractional_part = int(number), number % 1
почему в одну строчку?

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +    else:
Собственно, проблема в том, что всё что не 1 и не 2 распознаётся как 3, хотя не должно

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +def output_fp_64(whole_part, fractional_part, sign):
Правильно ли я понимаю, что эти `output_fp_64`, `output_fp_32`, `output_fp_64` по сути различаются только ограничениями форматов для мантиссы и порядка. Это повторяющийся код. Надо завернуть всё в одну и там в зависимости от введённого формата подставить нужные значения форматов мантиссы и порядка

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +        raise ValueError("incorrect number")
![image](https://github.com/ArtemKushnir/spbu_pyhton_sem1/assets/91395485/fb879214-c508-40af-aab4-cfdad4e0dd3b)

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +        raise ValueError("incorrect number")
Вообще некорректное поведение программы, это число

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +        raise ValueError("incorrect number")
Сообщение скорее должно быть Wrong format

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +    if number > 0:
эта проверка некорректна +0 и +0.0 превращаются в отрицательные нули

2023-11-14 22:35 UTC, Arsene-Baitenov commented on src/Homeworks/Homework4/Floating_numbers.py
> +        "0" * (11 - len(bin(change_order)[2:])) + bin(change_order)[2:]
ЯННП

2023-11-30 15:45 UTC, toadharvard requested changes
Функции названы очень странно, их содержание не до конца понятно. Разделение на функции должно быть более явным.
На ввод "123" выберется 3 вариант.

2023-11-30 15:46 UTC, closed without merging