Practice2. Task1. Kushnir
ArtemKushnir/spbu_pyhton_sem1 pull request #5
Opened 2023-09-22 11:37 UTC by ArtemKushnir

2023-10-04 20:20 UTC, toadharvard commented on src/practice/Practice2/Task1.py
> +        print("Ошибка")
И что мне сделать, чтобы исправить?

2023-10-04 20:30 UTC, toadharvard requested changes

2023-10-04 20:30 UTC, toadharvard commented on src/practice/Practice2/Task1.py
> +        print(f"Все подходящие дроби:", ", ".join(fractions(n)))
Может посортировать по значению?

2023-10-04 20:30 UTC, toadharvard commented on src/practice/Practice2/Task1.py
> +    else:
Пока считает результат ничего непонятно, так как ничего не выводится

2023-10-04 20:30 UTC, toadharvard commented on src/practice/Practice2/Task1.py
> +def fractions(n):
n^3 неоптимальное решение

2023-10-10 17:37 UTC, SpirinEgor requested changes
Использование словарей здесь явно избыточно

2023-10-10 17:37 UTC, SpirinEgor commented on src/practice/Practice2/Task1.py
> +    print("Введите число n")
Я бы тогда и тут еще добавил, что надо ввести не просто n, а знаменатель

2023-10-10 17:37 UTC, SpirinEgor commented on src/practice/Practice2/Task1.py
> +    return dict(sorted(res.items(), key=lambda item: item[1]))
А зачем словарь создавать?

2023-10-10 17:37 UTC, SpirinEgor commented on src/practice/Practice2/Task1.py
> +                res[f"{n1}/{n2}"] = n1 / n2
1. Из-за ошибок в точности результат может быть непредсказуемым
2. Дробь никак не проверяется на сократимость

2023-10-14 12:37 UTC, SpirinEgor requested changes

2023-10-14 12:37 UTC, SpirinEgor commented on src/practice/Practice2/Task1.py
> +            elif denominator % numerator != 0:
А если будет 6 15? Здесь не нулевой остаток, но дробь сократимая...

2023-10-14 12:37 UTC, SpirinEgor commented on src/practice/Practice2/Task1.py
> +    n = int(input())
Еще бы проверить, что это число

2023-10-16 07:50 UTC, SpirinEgor requested changes

2023-10-16 07:50 UTC, SpirinEgor commented on src/practice/Practice2/Task1.py
> +    return False
1. Есть довольно точное название у алгоритма/функции -- gcd
2. Есть встроенный `math.gcd`

2023-10-16 15:10 UTC, SpirinEgor approved these changes

2023-10-16 20:44 UTC, toadharvard approved these changes

2023-10-16 20:44 UTC, merged