Practice2. Task2. Kushnir
ArtemKushnir/spbu_pyhton_sem1 pull request #6
Opened 2023-09-22 12:14 UTC by ArtemKushnir

2023-10-04 20:19 UTC, toadharvard requested changes

2023-10-04 20:19 UTC, toadharvard commented on src/practice/Practice2/Task2.py
> +def bulls_and_cows(n1, n2, length):
Нейминг ужасен.

что такое n1 n2, почему функция это существительное?

2023-10-04 20:19 UTC, toadharvard commented on src/practice/Practice2/Task2.py
> +        return None
Неожиданное поведение у функции при равной длине. Потом будешь отлавливать 'NoneType' object is not subscriptable

2023-10-04 20:19 UTC, toadharvard commented on src/practice/Practice2/Task2.py
> +        if bulls_and_cows(n, my_number, k) is None:
Пересчитываешь 3 раза одно и то же, зачем?

2023-10-04 20:19 UTC, toadharvard commented on src/practice/Practice2/Task2.py
> +    number = "".join(
Бро...
Просто сгенерируй число от 1000 до 9999 и оберни в str зачем эти танцы?

2023-10-04 20:19 UTC, toadharvard commented on src/practice/Practice2/Task2.py
> +    n = input()
Добавь валидацию на инт, в уонце концов это игра про числа

2023-11-27 18:39 UTC, SpirinEgor approved these changes

2023-12-16 18:37 UTC, toadharvard approved these changes

2023-12-16 18:37 UTC, merged